### ISSUE TITLE
Updated css

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/pyos-sphinx-theme#20]
@sneakers-the-rat suggested some great changes here that i will merge to "ungoof-if-fy" our sphinx theme. we should add those same styles here so they can be applied across all of our books once we create a release! 

https://github.com/pyOpenSci/python-package-guide/pull/393/files

this is the css

```css
/* --------------------------------------
De-jumble header items.
See https://github.com/pydata/pydata-sphinx-theme/pull/1784
*/

.bd-header .bd-header__inner {
  padding: 0 1rem;
}

.bd-header .navbar-item {
  height: unset;
  max-height: unset;
}

@media (max-width: 960px) {
  .bd-header .navbar-header-items {
    flex-wrap: wrap;
    row-gap: 0.5rem;
  }
}

.bd-header .navbar-header-items__end,
.bd-header .navbar-header-items__center,
.bd-header .navbar-header-items__start {
  flex-flow: nowrap;
}

.bd-header .navbar-header-items__start {
  width: unset;
}

.bd-header .navbar-header-items__center {
  margin-right: 0.25em !important;
}

.bd-header ul.navbar-nav {
  flex-wrap: wrap;
}
```
